---
title: "Script_1"
output: html_document
date: "2024-09-13"
---
```{r}
library(readxl)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(lattice)
library(xml2)
library(hyperSpec)
library(R.utils)
library(ChemoSpecUtils)
library(ChemoSpec)
library(robustbase)
```
```{r}
data.1=read.csv("/Users/jorgeandresjolahernandez/Desktop/Publicaciones/Suelos_JuanPablo/Database_1.csv")

trans_df=data.1[,3:ncol(data.1)]
trans_df=as.data.frame(apply(trans_df, 2, function(x) log(1 / x)))

data.1 <- cbind(data.1[, 1:2], trans_df)
head(data.1)
```

```{r}
process <- function(value) {
  word <- gsub("[0-9]", "", value)
  if (word == "") {
    return("Composite")
  } else {
    return(word)
  }
}
Layer<- sapply(data.1$Layer, process)
data.1$Layer=Layer
data.1$Layer[data.1$Layer == "a"] <- "0-10"
data.1$Layer[data.1$Layer == "b"] <- "10-20"
data.1$Layer[data.1$Layer == "c"] <- "20-30"
data.1$Landscape[data.1$Landscape == "Plain"] <- "Pl"
data.1$Landscape[data.1$Landscape == "Mountain"] <- "M"
data.1$Landscape[data.1$Landscape == "Piedmont"] <- "P"
data.1$Landscape=as.factor(data.1$Landscape)
unique(data.1$Landscape)
Layer=as.vector(Layer)
head(data.1)
```
```{r}
means <- data.1 %>% 
  select(3:1503) %>% 
  group_by(data.1$Layer, data.1$Landscape) %>% 
  summarize_all(mean)
colnames(means)[1:2] <- c("Capa", "Landscape")
med <- data.frame(t(means))
names_col <- paste0(med[2, ],'_', med[1, ])
colnames(med) <- names_col
med<- med[-c(1:2), ]
med <- cbind(bands = rownames(med), med)
rownames(med) <- 1:nrow(med)
med$bands <- gsub("[Xx]", "", med$bands)
med$bands <- as.numeric(med$bands)
med$`Pl_0-10` <- as.numeric(med$`Pl_0-10`)
med$`M_0-10` <- as.numeric(med$`M_0-10`)
med$`P_0-10` <- as.numeric(med$`P_0-10`)
med$`Pl_10-20` <- as.numeric(med$`Pl_10-20`)
med$`M_10-20` <- as.numeric(med$`M_10-20`)
med$`P_10-20` <- as.numeric(med$`P_10-20`)
med$`Pl_20-30` <- as.numeric(med$`Pl_20-30`)
med$`M_20-30` <- as.numeric(med$`M_20-30`)
med$`P_20-30` <- as.numeric(med$`P_20-30`)
med$`Pl_Composite` <- as.numeric(med$`Pl_Composite`)
med$`M_Composite` <- as.numeric(med$`M_Composite`)
med$`P_Composite` <- as.numeric(med$`P_Composite`)
head(med)
```
```{r}
library(ggplot2)

ggplot(med, mapping = aes(x = bands)) +
  geom_point(aes(y = `P_0-10`, color = "Piedmont_a"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `P_10-20`, color = "Piedmont_b"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `P_20-30`, color = "Piedmont_c"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `P_Composite`, color = "Piedmont_Composite"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `Pl_0-10`, color = "Plain_a"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `Pl_10-20`, color = "Plain_b"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `Pl_20-30`, color = "Plain_c"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `Pl_Composite`, color = "Plain_Composite"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `M_0-10`, color = "Mountain_a"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `M_10-20`, color = "Mountain_b"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `M_20-30`, color = "Mountain_c"), size = 0.6, alpha = 0.4) +
  geom_point(aes(y = `M_Composite`, color = "Mountain_Composite"), size = 0.6, alpha = 0.4) +
  scale_x_continuous(limits = c(950, 2153), breaks = seq(350, 2500, by = 300)) +
  scale_y_continuous(limits = c(0.36, 1), breaks = seq(0, 0.9, by = 0.05)) +
  geom_text(aes(x = 1000, y = 0.38, label = "NIR"), color = "#CDB7B5", size = 5) +
  geom_text(aes(x = 1775, y = 0.38, label = "MIR"), color = "#CDB7B5", size = 5) +
  labs(x = "Bands", y = "Reflectance") +
  scale_color_manual(name = "Treatments", 
                     values = c("Piedmont_a" = "#1152F1", "Piedmont_b" = "#431697", 
                                "Piedmont_c" = "#32CD88", "Piedmont_Composite" = "#893419",
                                "Plain_a" = "#FFD700", "Plain_b" = "red", 
                                "Plain_c" = "#FF33A1", "Plain_Composite" = "#FF7F0E",
                                "Mountain_a" = "#2CA02C", "Mountain_b" = "#BCEE68", 
                                "Mountain_c" = "#CD3278", "Mountain_Composite" = "#76EEC6"),
                     labels = c("P 0-10", "P 10-20","P 20-30","P 0-30",
                                "Pl 0-10", "Pl 10-20","Pl 20-30","Pl 0-30",
                                "M 0-10", "M 10-20","M 20-30","M 0-30")) +
  geom_vline(xintercept = c(350, 400, 700, 1300), linetype = "dashed", color = "#8B7D7B") +
  theme_minimal() +
  theme(legend.position = "bottom", plot.title = element_text(size = 17, hjust = 0))+
  guides(color = guide_legend(override.aes = list(size = 3.5)))
```


```{r}
data.1 <- data.frame(t(data.1))
name_col <- paste0(data.1[2, ],'_', data.1[1, ])
colnames(data.1) <- name_col
data.1 <- data.1[-c(1:2), ]
data.1 <- cbind(bands = row.names(data.1), data.1)
rownames(data.1) <- 1:nrow(data.1)
data.1$bands <- gsub("X", "", data.1$bands)
data.1 <- lapply(data.1, as.numeric)
data.1 <- as.data.frame(data.1)
head(data.1)
```
```{r}
write.csv(data.1, "SpectraObject.csv", row.names = FALSE)

spectra_object <- matrix2SpectraObject (gr.crit =c(
  "Pl_Composite", "Pl_0.10", "Pl_10.20", "Pl_20.30",
  "P_Composite", "P_0.10", "P_10.20", "P_20.30",
  "M_Composite", "M_0.10", "M_10.20", "M_20.30"), 
                                        gr.cols <- c("darkgreen", "#66CDAA", "#CAFF70", "#A2CD5A",
             "brown", "darkgrey", "black", "grey", 
             "#FF7256", "red", "#FF82AB", "#9370DB"), 
                                        freq.unit = "nm",
                                        int.unit = "Reflectance intensity",
                                        descrip = "Three different landscapes and four depths",
                                        in.file = "SpectraObject.csv",
                                        out.file = "necro1", 
                                        sep = ",",
                                        dec = ".")
```

```{r}
levels(spectra_object$groups)
new_grps <- list(landscape = c("Pl", "M","P"), Layer= c("0.10", "10.20", "20.30","Composite"))
new_spectra <- splitSpectraGroups(spectra_object, new_grps)
PCAspectra <- aov_pcaSpectra(new_spectra, fac = c("landscape", "Layer"))
```
```{r}
p1spectra <- aovPCAscores(new_spectra, PCAspectra, submat = 3, ellipse = "cls") 
summary(aov(p1spectra$data$PC1~p1spectra$data$group))
p1spectra <- p1spectra + theme(legend.text = element_text(size = 70))
p1spectra
```
```{r}
spectra_object_A <- matrix2SpectraObject (gr.crit =c("M", "P","Pl"), 
                                        gr.cols = c("#66CDAA", "#FF82AB","black"),  
                                        freq.unit = "nm",
                                        int.unit = "Reflectance intensity",
                                        descrip = "Three Landscapes",
                                        in.file = "SpectraObject.csv",
                                        out.file = "necro2", 
                                        sep = ",",
                                        dec = ".")
```
###ANOVA-PCA Landscape
```{r}
levels(spectra_object_A$groups)
new_grpsland <- list(Landscape = c("A" ,"M" ,"Pl"))
new_spectra_A <- splitSpectraGroups(spectra_object_A, new_grpsland)
PCAspectra_A <- aov_pcaSpectra(new_spectra_A, fac = "Landscape")
```
```{r}
p2spectra_A <- aovPCAscores(new_spectra_A, PCAspectra_A, submat = 1, ellipse = "cls") 
summary(aov(p2spectra_A$data$PC1~p2spectra_A$data$group))
p2spectra_A <- p2spectra_A +theme(legend.text = element_text(size = 70))
p2spectra_A
```
###SPECTRA DEPTH
```{r}
spectra_object_A <- matrix2SpectraObject (gr.crit =c("0.10","10.20","20.30","Composite"), 
                                        gr.cols = c("#66CDAA", "#FF82AB","#FF7256","black"),  
                                        freq.unit = "nm",
                                        int.unit = "Reflectance intensity",
                                        descrip = "Three layers",
                                        in.file = "SpectraObject.csv",
                                        out.file = "necro2", 
                                        sep = ",",
                                        dec = ".")
```
###ANOVA-PCA DEPTH
```{r}
levels(spectra_object_A$groups)
new_grpsland <- list(Landscape = c("a" ,"b" ,"c","Composite"))
new_spectra_A <- splitSpectraGroups(spectra_object_A, new_grpsland)
PCAspectra_A <- aov_pcaSpectra(new_spectra_A, fac = "Landscape")
```
###GRAFICOS DEPTH
```{r}
p3spectra_A <- aovPCAscores(new_spectra_A, PCAspectra_A, submat = 1, ellipse = "cls") 
summary(aov(p3spectra_A$data$PC1~p3spectra_A$data$group))
p3spectra_A <- p3spectra_A + theme(legend.text = element_text(size = 50))
p3spectra_A
```


